# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rover.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rover.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brover.proto\x12\x05rover\"\x07\n\x05\x45mpty\"7\n\x0bMapResponse\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x02 \x01(\x05\x12\x0c\n\x04grid\x18\x03 \x03(\x05\" \n\x0cRoverRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\"\x1a\n\x07\x43ommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"%\n\x11MineSerialRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\"$\n\x12MineSerialResponse\x12\x0e\n\x06serial\x18\x01 \x01(\t\"1\n\x0cStatusReport\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x1c\n\tStatusAck\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x07MinePin\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\x12\x0b\n\x03pin\x18\x02 \x01(\x05\"\x19\n\x06PinAck\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9c\x02\n\x0cRoverService\x12*\n\x06GetMap\x12\x0c.rover.Empty\x1a\x12.rover.MapResponse\x12\x34\n\x0bGetCommands\x12\x13.rover.RoverRequest\x1a\x0e.rover.Command0\x01\x12\x44\n\rGetMineSerial\x12\x18.rover.MineSerialRequest\x1a\x19.rover.MineSerialResponse\x12\x35\n\x0cReportStatus\x12\x13.rover.StatusReport\x1a\x10.rover.StatusAck\x12-\n\x0cShareMinePin\x12\x0e.rover.MinePin\x1a\r.rover.PinAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rover_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_MAPRESPONSE']._serialized_start=31
  _globals['_MAPRESPONSE']._serialized_end=86
  _globals['_ROVERREQUEST']._serialized_start=88
  _globals['_ROVERREQUEST']._serialized_end=120
  _globals['_COMMAND']._serialized_start=122
  _globals['_COMMAND']._serialized_end=148
  _globals['_MINESERIALREQUEST']._serialized_start=150
  _globals['_MINESERIALREQUEST']._serialized_end=187
  _globals['_MINESERIALRESPONSE']._serialized_start=189
  _globals['_MINESERIALRESPONSE']._serialized_end=225
  _globals['_STATUSREPORT']._serialized_start=227
  _globals['_STATUSREPORT']._serialized_end=276
  _globals['_STATUSACK']._serialized_start=278
  _globals['_STATUSACK']._serialized_end=306
  _globals['_MINEPIN']._serialized_start=308
  _globals['_MINEPIN']._serialized_end=348
  _globals['_PINACK']._serialized_start=350
  _globals['_PINACK']._serialized_end=375
  _globals['_ROVERSERVICE']._serialized_start=378
  _globals['_ROVERSERVICE']._serialized_end=662
# @@protoc_insertion_point(module_scope)
