# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rover_pb2 as rover__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rover_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoverServiceStub(object):
    """The service definition. Each method corresponds to one of the five actions.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/rover.RoverService/GetMap',
                request_serializer=rover__pb2.Empty.SerializeToString,
                response_deserializer=rover__pb2.MapResponse.FromString,
                _registered_method=True)
        self.GetCommands = channel.unary_stream(
                '/rover.RoverService/GetCommands',
                request_serializer=rover__pb2.RoverRequest.SerializeToString,
                response_deserializer=rover__pb2.Command.FromString,
                _registered_method=True)
        self.GetMineSerial = channel.unary_unary(
                '/rover.RoverService/GetMineSerial',
                request_serializer=rover__pb2.MineSerialRequest.SerializeToString,
                response_deserializer=rover__pb2.MineSerialResponse.FromString,
                _registered_method=True)
        self.ReportStatus = channel.unary_unary(
                '/rover.RoverService/ReportStatus',
                request_serializer=rover__pb2.StatusReport.SerializeToString,
                response_deserializer=rover__pb2.StatusAck.FromString,
                _registered_method=True)
        self.ShareMinePin = channel.unary_unary(
                '/rover.RoverService/ShareMinePin',
                request_serializer=rover__pb2.MinePin.SerializeToString,
                response_deserializer=rover__pb2.PinAck.FromString,
                _registered_method=True)


class RoverServiceServicer(object):
    """The service definition. Each method corresponds to one of the five actions.
    """

    def GetMap(self, request, context):
        """1. Get the map (the 2D land array)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommands(self, request, context):
        """2. Get a stream of commands (each command is sent as a separate message)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMineSerial(self, request, context):
        """3. Get a mine serial number
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStatus(self, request, context):
        """4. Report execution status (whether all commands were executed successfully)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareMinePin(self, request, context):
        """5. Share a mine PIN (after disarming a mine) with the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=rover__pb2.Empty.FromString,
                    response_serializer=rover__pb2.MapResponse.SerializeToString,
            ),
            'GetCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCommands,
                    request_deserializer=rover__pb2.RoverRequest.FromString,
                    response_serializer=rover__pb2.Command.SerializeToString,
            ),
            'GetMineSerial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMineSerial,
                    request_deserializer=rover__pb2.MineSerialRequest.FromString,
                    response_serializer=rover__pb2.MineSerialResponse.SerializeToString,
            ),
            'ReportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStatus,
                    request_deserializer=rover__pb2.StatusReport.FromString,
                    response_serializer=rover__pb2.StatusAck.SerializeToString,
            ),
            'ShareMinePin': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareMinePin,
                    request_deserializer=rover__pb2.MinePin.FromString,
                    response_serializer=rover__pb2.PinAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rover.RoverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rover.RoverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoverService(object):
    """The service definition. Each method corresponds to one of the five actions.
    """

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.RoverService/GetMap',
            rover__pb2.Empty.SerializeToString,
            rover__pb2.MapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rover.RoverService/GetCommands',
            rover__pb2.RoverRequest.SerializeToString,
            rover__pb2.Command.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMineSerial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.RoverService/GetMineSerial',
            rover__pb2.MineSerialRequest.SerializeToString,
            rover__pb2.MineSerialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.RoverService/ReportStatus',
            rover__pb2.StatusReport.SerializeToString,
            rover__pb2.StatusAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareMinePin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.RoverService/ShareMinePin',
            rover__pb2.MinePin.SerializeToString,
            rover__pb2.PinAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
